# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r requirements.txt
            pip install -q twine

      - save_cache:
          paths:
            - ./venv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest

      - run:
          name: build package
          branches:
            only:
              - rc
              - master
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel

      - run:
          name: deploy release candidate
          branches:
            only:
              - rc
          command: |
            . venv/bin/activate
            twine upload --repository testpypi dist/*

      - run:
          name: deploy release
          branches:
            only:
              - master
          command: |
            . venv/bin/activate
            twine upload --repository pypi dist/*

#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
